//
// Created by asgyu on 2026. márc. 7..
//

#ifndef SNAILSPACE_VISUAL_NOVEL_STATE_H
#define SNAILSPACE_VISUAL_NOVEL_STATE_H

#include "game_manager.h"
#include "game_types.h"
#include "ui_manager.h"
#include "visual_novel.h"

typedef enum{
    SPEAKER_PLAYER,
    SPEAKER_DEALER,
    SPEAKER_HELSIE,
} SpeakerID;

typedef enum{
    DLG_INTRO,
    DLG_GYULASZ_CALM_HIMSELF_DOWN,
    DLG_DEALER_GREETING,
    DLG_PLAYER_SEARCHING_HELSIE,
    DLG_HELSIE_GREETING,
    DLG_GYULASZ_GREETING_HELSIE,
    DLG_DEALER_KNOWS_HELSIE,
    DLG_GYULASZ_EYES_SPARKING,
    DLG_DEALER_MAKE_AN_OFFER,
    DLG_DEALER_MAKE_AN_OFFER2,
    DLG_GYULASZ_ASKING_ABOUT_OFFER,
    DLG_DEALERS_MAKE_A_DEAL,
    DLG_GYULASZ_READING_THE_OFFER,
    DLG_GYULASZ_READING_THE_OFFER2,
    DLG_DEALER_MAKE_A_DEAL2,
    DLG_MONSTER_APPEARS,
    DLG_GYULASZ_SIGN_THE_CONTRACT,
    DLG_GYULASZ_SIGN_THE_CONTRACT2,
    DLG_SCENE_SWITCH_BAT_VISION,
    DLG_IN_THE_BAT_VISION,
    DLG_IN_THE_BAT_VISION2,
    DLG_IN_THE_BAT_VISION_SNAIL,
    DLG_IN_THE_BAT_VISION_SNAIL2,
    DLG_IN_THE_BAT_VISION_SNAIL3,
    DLG_IN_THE_BAT_VISION_SNAIL4,
    DLG_IN_THE_BAT_VISION_SNAIL5,
    DLG_GYULASZ_SEE_NOTHING,
    DLG_GYULASZ_SEE_NOTHING2,
    DLG_GYULASZ_SEE_NOTHING3,
    DLG_GYULASZ_SEE_NOTHING4,
    DLG_HELSIE_TELL_ABOUT_MONSTRUMS,
    DLG_HELSIE_TELL_ABOUT_MONSTRUMS2,
    DLG_HELSIE_TELL_ABOUT_MONSTRUMS3,
    DLG_GYULASZ_REPLY_TO_MONSTRUMS,
    DLG_GYULASZ_REPLY_TO_MONSTRUMS2,
    DLG_MITA_SAVES_PLAYER,
    DLG_PLAYER_THX_TO_MITA,
    DLG_MITA_SAVES_PLAYER2,
    DLG_PLAYER_THX_TO_MITA2,
    DLG_MITA_OPEN_PLAYERS_EYES,
    DLG_MITA_OPEN_PLAYERS_EYES2,
    DLG_MITA_INVITATION,
    DLG_PLAYER_ACCEPT_MITAS_INVITATION,
    DLG_PLAYER_ACCEPT_MITAS_INVITATION2,
    DLG_COUNT
} DialogueID;

Dialogue create_dialogue_from_id(DialogueID id, const char* name_placeholder, const UIElement* player_speaker_img);

void handle_mouse_input_visual_novel(SDL_Event* event, VisualNovelState* visual_novel_state, Dialogue* dialogue, TextureAssets* texture_assets);

#endif //SNAILSPACE_VISUAL_NOVEL_STATE_H